# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Trigger-Ordered
version:      0.01
version_from: lib/Class/Trigger/Ordered.pm
installdirs:  site
requires:
    Class::Trigger:                0.1
    Test::More:                    0.62

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
